name: Quantize Release

on: 
  push:
    tags:
      - "alpha*"
      - "beta*"
      - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      caller: "release"

  release:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: quantize-win64-${{ github.sha }}

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: quantize-linux-${{ github.sha }}

      - name: Re-Compress
        run: |
          zip quantize-${{
            github.event_name == 'push' && github.ref_name || 'DRY_RUN'
          }}-win-x86_64.zip quantize.dll
          zip quantize-${{
            github.event_name == 'push' && github.ref_name || 'DRY_RUN'
          }}-linux-x86_64.zip quantize.so

      - name: Create Release
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "quantize-${{github.ref_name}}-*-x86_64.zip"
          body: |
            # Quantize Release ${{ github.ref_name }}
            Check the [changelog](changelog.md) for updates

